travis:
  secure:
    BINSTAR_TOKEN: KlF7jNbVBCI5K/1mmWHaPFG5uGGenTVsEc3L7rdyRHpLL5LFPMU/CXOm74b6UuHRXm9q4Ncv0G9TAXzHgznhihCMg26Ol6pfOfSCdrWotUUXDR5rrEDVcncBc3TTUk20yRJF2runPmxjykdcjthH56/mJInf2LKpHkAKZhJNSbCHU4tcrA5UEzHQsmNKVRZfT94nItsUVFyjWjKY7tiAD36qDpCZG4+FX+5WnKIncZicfd60ZbPUIAKbk0CkbCyV+BK1X97wcyPshXhk7bNjDweheJbgeIk83L8S8uqmSZAaiyg2lH5TAlWZ5vqep9N3/EHNm4XhJfbcv2w/EjXE/dPtEn8KaojeTh+kcgyGAd7mr/ZWw+4tLJoVTY/mjDFyewDQINN+dlaG9fiGe5VK9Mw8MFIWvd6XdIKeTrM9PqFuT6IvOl5UL5vS2LVeJ5X8ZmWwb2PECD/Fb28t3+irHQ1HdKFSd8J2M7yhgrFxgJiqyebGHCTSqSrAxui4Qt0scbWhWMZWpkusmMkaYgo4FMOuDASvcg+1W63NNX+td6AA5V5lfXIrneVBHvwhUAo2siVZHtwY9Llht6xpT0QVXqAJyTfFfSI7a9ZRk1s+q9ZiyWWshaxGC1PRDnUeSoH1q6l4PyUeljVy0QvqbfaDB0f+t0PjaMvmImp3PMUAR68=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
